const data = {
    products: [
        {
            _id: '1',
            name: 'Sutra',
            category: 'Mukenah',
            image: '/images/product-1.jpg',
            price: 250,
            brand: 'Sanskrit',
            rating: 4.9,
            numReviews: 20,
            countInStock: 10,
        },
        {
            _id: '2',
            name: 'Cendana',
            category: 'Mukenah',
            image: '/images/product-2.jpg',
            price: 200,
            brand: 'Sanskrit',
            rating: 4.8,
            numReviews: 15,
            countInStock: 8,
        },
        {
            _id: '3',
            name: 'Anggita',
            category: 'Mukenah',
            image: '/images/product-3.jpg',
            price: 180,
            brand: 'Sanskrit',
            rating: 4.7,
            numReviews: 12,
            countInStock: 5,
        },
        {
            _id: '4',
            name: 'Pranaya',
            category: 'Mukenah',
            image: '/images/product-4.jpg',
            price: 220,
            brand: 'Sanskrit',
            rating: 4.9,
            numReviews: 18,
            countInStock: 7,
        },
        {
            _id: '5',
            name: 'Mahesa',
            category: 'Mukenah',
            image: '/images/product-5.jpg',
            price: 230,
            brand: 'Sanskrit',
            rating: 4.8,
            numReviews: 16,
            countInStock: 9,
        },
        {
            _id: '6',
            name: 'Ratna',
            category: 'Mukenah',
            image: '/images/product-6.jpg',
            price: 210,
            brand: 'Sanskrit',
            rating: 4.7,
            numReviews: 14,
            countInStock: 6,
        },
        // {
        //     _id: '7',
        //     name: 'Indira',
        //     category: 'Mukenah',
        //     image: '/images/mukenah-indira.jpg',
        //     price: 240,
        //     brand: 'Sanskrit',
        //     rating: 4.9,
        //     numReviews: 19,
        //     countInStock: 8,
        // },
        // {
        //     _id: '8',
        //     name: 'Laksmi',
        //     category: 'Mukenah',
        //     image: '/images/mukenah-laksmi.jpg',
        //     price: 260,
        //     brand: 'Sanskrit',
        //     rating: 5.0,
        //     numReviews: 22,
        //     countInStock: 10,
        // }
    ]
}
export default data;